### ISSUE TITLE
SDL2 support?

### ISSUE THREAD

**Issue by sfan5** [tpoechtrager/wc-ng#1]
README.md says that wc-ng works with SDL2.
There doesn't seem to be any code for SDL2 and changing `sdl-config` to `sdl-config2` in the Makefile causes compliation errors.

**Comment by Croydon** [comment]
There is a SDL2 branch. However, I'm wondering why this isn't the default.

**Comment by tpoechtrager** [comment]
```
git checkout sdl2
```

:smile:

SDL2 isn't default because pisto's port changes the mouse sensitivity,
doubles the cpu time and slows down map loading :/.
