### ISSUE TITLE
Reconnecting to server after being kicked results into a message error (Even if I have auth key for the server)

### ISSUE THREAD

**Issue by sata1122** [tpoechtrager/wc-ng#10]
Reconnecting to a sauer server after being kicked results in a message error (Even if I have auth key for the server).
Also "autoauth = 1" and default server auth domain is the same as my key.
Tested this in Vanilla client too. Vanilla client works perfectly and I am able to reconnect with my auth key just fine.

Here is the link to screenshot:
https://ibb.co/vZ1tFv1

**Comment by tpoechtrager** [comment]
Fixed. Thanks for reporting the issue.
