### ISSUE TITLE
0.00 ms ping on certain servers

### ISSUE THREAD

**Issue by Jed-** [tpoechtrager/wc-ng#14]
The popular "RUGBY iCTF" server recently switched to a new method to calculate ping on the server side.
`N_PONG` messages are no longer sent and, as a result, the `highresping` value is never updated for player1 and the bottom right corner of the screen always reads "0.00 ms".

**Comment by tpoechtrager** [comment]
Thank you. New builds available @ https://wc-ng.mooo.com/sauerbraten_2020/2021-07-17/.
