### ISSUE TITLE
sdl2 upstream + collect compatibility

### ISSUE THREAD

**Issue by pisto** [tpoechtrager/wc-ng#3]
I have a hybrid SVN upstream with collect server compatibility here https://github.com/pisto/sdos-test/commits/sdl2-upstream . Mind porting wc-ng sdl2 to that?

**Comment by pisto** [comment]
Here's my WIP about it https://github.com/pisto/sdos-test/tree/wc-ng-upstream . It's a rather naive merge of SVN tip, my C2SVN changes (embedded data/, hybrid collect-svn protocol compatibility) and wc-ng, so a different set of eyes could really help.

**Comment by tpoechtrager** [comment]
Whoops, I totally overlooked this. Sorry. I will have a look at it next week.
