### ISSUE TITLE
Porting back some features to TQ

### ISSUE THREAD

**Issue by Fohlen** [tpoechtrager/wc-ng#7]
Dear @tpoechtrager ,

would you be interested in porting back some of these features into https://github.com/tomatenquark/code ?

Specifically the demo playback and gamehud functionality sounds very interesting to me.
I haven't had a chance yet to review the code, how much work would it be to isolate the changes?

All the best

**Comment by tpoechtrager** [comment]
Hey,

thanks for your interest in my mods. You are of course free to implement them in your fork.

I personally want to keep working on my own project. Doesn't mean I wouldn't appreciate your Sauerbraten fork!

The modifications are heavily dependent on the stuff in `src/mod/*`.

**Comment by Fohlen** [comment]
Okay I'll take a look, thanks!
